<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Persistence\Database\Resources\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.79" />
    <PackageReference Include="EPPlus" Version="8.6.3" />
    <PackageReference Include="MySql.Data" Version="26.7.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SmartMix.Core.Application\SmartMix.Core.Application.csproj" />
    <ProjectReference Include="..\SmartMix.Core.Domain\SmartMix.Core.Domain.csproj" />
  </ItemGroup>

</Project>